config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
 namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_ditails, only: [:update]
    root to: "homes#top"
 end

   scope module: :public do
   root to: "homes#top"
   get '/about' => 'homes#about', as: 'about'
   resources :items, only: [:index, :show]
   resource :customers, only: [:show, :edit, :update] do
   collection do
    get 'withdraw'
    patch 'unsubscribe'
   end
    end
   resources :cart_items, only: [:index, :create, :update, :destroy] do
   collection do
   delete 'destroy_all'
  end
   end
    resources :orders, only: [:index, :create, :new, :show] do
   collection do
   get 'complete'
   post 'confirm'
   end
   end
   resources :addresses, only: [:index, :create, :edit, :update, :destroy]
 end


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
 belongs_to :customer
 def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
 end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 has_many :addresses, dependent: :destroy
 has_many :cart_items, dependent: :destroy
 has_many :orders, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
 has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
 belongs_to :genre
 has_many :cart_items, dependent: :destroy
 has_many :order_ditails, dependent: :destroy
 has_one_attached :image

 def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  image.variant(resize_to_limit: [width, height]).processed
 end

 def with_tax_price
    (price * 1.1).floor
 end

end

app/models/order.rb
class Order < ApplicationRecord
 belongs_to :customer
 has_many :order_ditails, dependent: :destroy
enum payment_method: { credit_card: 0, transfer: 1 }
enum status: { waiting_for_payment: 0, payment_confirmation: 1, in_production: 2, preparing_for_shipment: 3, shipped: 4 }
 def subtotal
    item.with_tax_price * amount
 end
end

app/models/order_ditail.rb
class OrderDitail < ApplicationRecord
 belongs_to :order
 belongs_to :item
 enum making_status: { not_allowed_to_produce: 0, production_waiting: 1, in_production: 2, production_completed: 3 }
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
 def index
  @customers = Customer.all.page(params[:page])
 end

 def show
  @customer = Customer.find(params[:id])
 end

 def edit
  @customer = Customer.find(params[:id])
 end

 def update
  @customer = Customer.find(params[:id])
  @customer.update(customer_params)
  redirect_to admin_customer_path(@customer.id)
 end

 private

 def customer_params
  params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
 end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
 def index
  @genres = Genre.all
  @genre = Genre.new
 end

 def create
  @genre = Genre.new(genre_params)
  @genre.save
   redirect_to admin_genres_path
 end

 def edit
  @genre = Genre.find(params[:id])
 end

 def update
  @genre = Genre.find(params[:id])
  @genre.update(genre_params)
  redirect_to admin_genres_path(@genre.id)
 end

 private

 def genre_params
  params.require(:genre).permit(:name)
 end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
 before_action :authenticate_admin!
 def top
  @orders = Order.page(params[:page])
 end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
 def new
  @item = Item.new
 end

 def index
  @items = Item.all.page(params[:page])
 end

 def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_item_path(@item.id)
 end

 def show
  @item = Item.find(params[:id])
 end

 def edit
  @item = Item.find(params[:id])
 end

 def update
  @item = Item.find(params[:id])
  @item.update(item_params)
  redirect_to admin_items_path(@item.id)
 end

 private

 def item_params
  params.require(:item).permit(:name,:introduction,:image,:genre_id,:price,:is_active)
 end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
   @order = Order.find(params[:id])
   @order_ditails = @order.order_ditails
   @total = 0
  end

  def update
   @order = Order.find(params[:id])
   @order.update(order_params)
   redirect_to  admin_order_path
  end

  private
  def order_params
      params.require(:order).permit(:status)
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_ditails_helper.rb
module Admin::OrderDitailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-12">
   <h4 class= "mt-3 mb-4">
    <%= @customer.first_name %>
    <%= @customer.last_name %>
     さんの会員情報編集
   </h4>
    <%= form_with model: @customer, url: admin_customer_path(@customer), method: :patch do |f| %>

   <div class="row">
    <div class="col-md-2 mb-2">
     会員ID
    </div>
    <div class="col-md-5">
     <%= @customer.id %>
    </div>
   </div>
   <div class="row">
    <div class="col-md-2 my-1">
     氏名
    </div>
    <div class="col-md-3 my-1">
     <%= f.text_field :first_name %>
    </div>
    <div class="col-md-3 my-1">
     <%= f.text_field :last_name %>
    </div>
   </div>
   <div class="row">
    <div class="col-md-2 my-1">
     フリガナ
    </div>
    <div class="col-md-3 my-1">
     <%= f.text_field :first_name_kana %>
    </div>
    <div class="col-md-3 my-1">
     <%= f.text_field :last_name_kana %>
    </div>
   </div>
   <div class="row">
    <div class="col-md-3 my-1">
     郵便番号
    </div>
    <div class="col-md-3 my-1">
     <%= f.text_field :postal_code %>
    </div>
   </div>
   <div class="row">
    <div class="col-md-3">
     住所
    </div>
    <div class="col-md-3 my-1">
     <%= f.text_field :address %>
    </div>
   </div>
   <div class="row">
    <div class="col-md-3 my-1">
     電話番号
    </div>
    <div class="col-md-3 my-1">
     <%= f.text_field :telephone_number %>
    </div>
   </div>
    <div class="row">
    <div class="col-md-3 my-1">
     メールアドレス
    </div>
    <div class="col-md-3 my-1">
     <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>
   </div>
   <div class="row">
    <div class="col-md-3 my-1">
    会員ステータス
    </div>

    <div class="col-md-3 my-1 row">
     <h5><%= f.radio_button :is_deleted, true %>有効</h5>
     <h5 class= "ml-3"><%= f.radio_button :is_deleted, false %>退会</h5>
    </div>
   </div>
   <div class="offset-md-3">
    <%= f.submit "変更を保存",class:"btn btn-success" %>
   </div>
  <% end %>
  </div>
 </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-12">
  <h4 class= "mt-3 mb-5">会員一覧</h4>

  <div class="col-md-8 offset-md-1">
    <table class="table table-hover table-inverse">
     <thead>
      <tr>
       <th>会員ID</th>
       <th>氏名</th>
       <th>メールアドレス</th>
       <th>ステータス</th>
      </tr>
     </thead>
     <tbody>
      <% @customers.each do |customer| %>
       <tr>
        <td><%= customer.id %></td>
        <td>
        <%= link_to admin_customer_path(customer.id) do %>
        <%= customer.first_name %>
        <%= customer.last_name %>
         <% end %>
        </td>
        <td><%= customer.email %></td>
        <td>
         <% if customer.is_deleted == false %>
          有効
         <% elsif customer.is_deleted == true %>
          退会
         <% end %>
        </td>
       </tr>
      <% end %>
     </tbody>
    </table>
     <%= paginate @customers %>
   </div>
  </div>
 </div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
   <div class="col-md-12">
    <h4 class= "mt-3 mb-5">
      <%= @customer.first_name %>
      <%= @customer.last_name %>
      さんの会員詳細
    </h4>

    <div class="row">
     <div class="col-md-2 mb-2">
      会員ID
     </div>
     <div class="col-md-5">
      <%= @customer.id %>
     </div>
   </div>
   <div class="row">
    <div class="col-md-2 my-1">
     氏名
    </div>
    <div class="col-md-3 my-1">
     <%= @customer.first_name %>
     <%= @customer.last_name %>
    </div>
   </div>
   <div class="row">
    <div class="col-md-2 my-1">
     フリガナ
    </div>
    <div class="col-md-3 my-1">
     <%= @customer.first_name_kana %>
     <%= @customer.last_name_kana %>
    </div>
   </div>
   <div class="row">
    <div class="col-md-2 my-1">
     郵便番号
    </div>
    <div class="col-md-3 my-1">
     <%= @customer.postal_code %>
    </div>
   </div>
   <div class="row">
    <div class="col-md-2 my-1">
     住所
    </div>
    <div class="col-md-3 my-1">
     <%= @customer.address %>
    </div>
   </div>
   <div class="row">
    <div class="col-md-2 my-1">
     電話番号
    </div>
    <div class="col-md-3 my-1">
     <%= @customer.telephone_number %>
    </div>
   </div>
   <div class="row">
    <div class="col-md-2 my-1">
     メールアドレス
    </div>
    <div class="col-md-3 my-1">
     <%= @customer.email %>
    </div>
   </div>
   <div class="row">
    <div class="col-md-2 my-1">
    会員ステータス
    </div>
    <div class="col-md-3 my-1 row">
      <% if @customer.is_deleted == false %>
          有効
      <% elsif @customer.is_deleted == true %>
         退会
     <% end %>
    </div>
   </div>
   <div class="col-md-9 offset-md-1 row">
    <div>
     <%= link_to "編集する", edit_admin_customer_path(@customer.id),class:"btn btn-sm btn-success" %>
    </div>
    <div class="offset-md-1">
     <%= link_to "注文履歴一覧を見る", admin_root_path,class:"btn btn-primary" %>
    </div>
   </div>
  </div>
</div>
</div>