config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
 namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_ditails, only: [:update]
    root to: "homes#top"
 end

   scope module: :public do
   root to: "homes#top"
   get '/about' => 'homes#about', as: 'about'
   resources :items, only: [:index, :show]
   resource :customers, only: [:show, :edit, :update] do
   collection do
    get 'withdraw'
    patch 'unsubscribe'
   end
    end
   resources :cart_items, only: [:index, :create, :update, :destroy] do
   collection do
   delete 'destroy_all'
  end
   end
    resources :orders, only: [:index, :create, :new, :show] do
   collection do
   get 'complete'
   post 'confirm'
   end
   end
   resources :addresses, only: [:index, :create, :edit, :update, :destroy]
 end


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
 belongs_to :customer
 def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
 end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 has_many :addresses, dependent: :destroy
 has_many :cart_items, dependent: :destroy
 has_many :orders, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
 has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
 belongs_to :genre
 has_many :cart_items, dependent: :destroy
 has_many :order_ditails, dependent: :destroy
 has_one_attached :image

 def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  image.variant(resize_to_limit: [width, height]).processed
 end

 def with_tax_price
    (price * 1.1).floor
 end

end

app/models/order.rb
class Order < ApplicationRecord
 belongs_to :customer
 has_many :order_ditails, dependent: :destroy
enum payment_method: { credit_card: 0, transfer: 1 }
enum status: { waiting_for_payment: 0, payment_confirmation: 1, in_production: 2, preparing_for_shipment: 3, shipped: 4 }
 def subtotal
    item.with_tax_price * amount
 end
end

app/models/order_ditail.rb
class OrderDitail < ApplicationRecord
 belongs_to :order
 belongs_to :item
 enum making_status: { not_allowed_to_produce: 0, production_waiting: 1, in_production: 2, production_completed: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
 def index
  @genres = Genre.all
  @genre = Genre.new
 end

 def create
  @genre = Genre.new(genre_params)
  @genre.save
   redirect_to admin_genres_path
 end

 def edit
  @genre = Genre.find(params[:id])
 end

 def update
  @genre = Genre.find(params[:id])
  @genre.update(genre_params)
  redirect_to admin_genres_path(@genre.id)
 end

 private

 def genre_params
  params.require(:genre).permit(:name)
 end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
 before_action :authenticate_admin!
 def top
  @orders = Order.page(params[:page])
 end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
 def new
  @item = Item.new
 end

 def index
  @items = Item.all.page(params[:page])
 end

 def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_item_path(@item.id)
 end

 def show
  @item = Item.find(params[:id])
 end

 def edit
  @item = Item.find(params[:id])
 end

 def update
  @item = Item.find(params[:id])
  @item.update(item_params)
  redirect_to admin_items_path(@item.id)
 end

 private

 def item_params
  params.require(:item).permit(:name,:introduction,:image,:genre_id,:price,:is_active)
 end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
   @order = Order.find(params[:id])
   @order_ditails = @order.order_ditails
   @total = 0
  end

  def update
   @order = Order.find(params[:id])
   @order.update(order_params)
   redirect_to  admin_order_path
  end

  private
  def order_params
      params.require(:order).permit(:status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
   def after_sign_in_path_for(resource)
    admin_root_path
   end

   def after_sign_out_path_for(resource)
    new_admin_session_path
   end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_ditails_helper.rb
module Admin::OrderDitailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-12">
   <h4 class= "mt-3 mb-5">ジャンル編集</h4>

 <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>

<table class= "my-5">
    <thead>
     <tr>
      <th></th>
      <th></th>
     </tr>
    </thead>
     <tbody>
      <tr>
       <th>ジャンル名 </th>
       <th class= "px-5"><%= f.text_field :name %></th>
       <th><%= f.submit '変更を保存',class:"btn btn-success" %></th>
      </tr>
     </tbody>
   </table>
     <% end %>
     </div>
 </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-12">
   <h4 class= "mt-3 mb-5">ジャンル一覧・追加</h4>
   <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
   <table class= "my-5">
    <thead>
     <tr>
      <th></th>
      <th></th>
     </tr>
    </thead>

     <tbody>
      <tr>
       <th>ジャンル名</th>
       <th class= "px-5"><%= f.text_field :name %></th>
       <th><%= f.submit '新規登録',class:"btn btn-success" %></th>
      </tr>
     </tbody>
   </table>
     <% end %>
   <div class="col-md-6">
    <table class="table table-hover table-inverse">
     <thead>
      <tr></tr>
      <tr></tr>
     </thead>
     <tbody>
      <tr>
       <th>ジャンル</th>
      </tr>
       <% @genres.each do |genre| %>
      <tr>
       <td><%= genre.name %></td>
       <td><%= link_to "編集する", edit_admin_genre_path(genre.id),class:"btn btn-sm btn-success" %></td>
     </tr>
       <% end %>
     </tbody>
    </table>
   </div>
  </div>
 </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
 <div class="row">
  <div class="mx-auto">
   <h4 class= "mt-3 mb-5">商品編集</h4>
    <%= form_with model: @item, url: admin_item_path(@item), method: :patch do |f| %>

    <div class='form-group row'>
     <%= f.label :image, "商品画像", class: "col-4" %>
     <%= f.file_field :image, accept: "image/*", class: "col-8" %>
    </div>

    <div class='form-group row'>
     <%= f.label :name, "商品名", class: "col-4" %>
     <%= f.text_field :name, class: "col-8" %>
    </div>

    <div class='form-group row'>
     <%= f.label :introduction, "説明", class: "col-4" %>
     <%= f.text_area :introduction, class: "col-8" %>
    </div>

    <div class='form-group row'>
     <%= f.label :genre_id, "ジャンル", class: "col-4" %>
     <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), { include_blank: "選択してください" }, class: "col-8" %>
    </div>

    <div class='form-group row'>
     <%= f.label :price, "税抜き価格", class: "col-4" %>
     <%= f.text_field :price, class: "col-7" %>円
    </div>

    <div class='form-group row'>
     <%= f.label :is_active, "販売ステータス", class: "col-4" %>
     <h5><%= f.radio_button :is_active, true %>販売中</h5>
     <h5 class= "ml-3"><%= f.radio_button :is_active, false %> 販売停止</h5>
    </div>

    <div class="text-center"><%= f.submit '変更を保存',class:"btn btn-success" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
 <div class="row">
  <div class="col-md-12">
  <h4 class= "mt-3 mb-5">商品一覧</h4>

  <div class="col-md-8 offset-md-1">
    <table class="table table-hover table-inverse">
     <thead>
      <tr>
       <th>商品ID</th>
       <th>商品名</th>
       <th>税抜き価格</th>
       <th>ジャンル</th>
       <th>ステータス</th>
      </tr>
     </thead>
     <tbody>
      <% @items.each do |item| %>
       <tr>
        <td><%= item.id %></td>
        <td>
        <%= link_to admin_item_path(item.id) do %>
        <%= item.name %>
         <% end %>
        </td>
        <td><%= item.price %></td>
        <td><%= item.genre.name %></td>
        <td>
        <% if item.is_active == true %>
          販売中
        <% elsif item.is_active == false %>
          販売停止中
        <% end %>
        </td>
       </tr>
      <% end %>
     </tbody>
    </table>
    <div class="text-center">
    　<%= link_to "新規登録", new_admin_item_path,class:"btn btn-success" %>
    </div>
     <%= paginate @items %>
   </div>
  </div>
 </div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h4 class= "mt-3 mb-5">商品新規登録</h4>
      <%= form_with model: @item, url: admin_items_path, method: :post do |f| %>

        <div class='form-group row'>
          <%= f.label :image, "商品画像", class: "col-4" %>
          <%= f.file_field :image, accept: "image/*", class: "col-8" %>
        </div>

        <div class='form-group row'>
         <%= f.label :name, "商品名", class: "col-4" %>
         <%= f.text_field :name, class: "col-8" %>
        </div>

        <div class='form-group row'>
         <%= f.label :introduction, "説明", class: "col-4" %>
         <%= f.text_area :introduction, class: "col-8" %>
        </div>

        <div class='form-group row'>
         <%= f.label :genre_id, "ジャンル", class: "col-4" %>
         <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), { include_blank: "選択してください" }, class: "col-8" %>
        </div>

        <div class='form-group row'>
         <%= f.label :price, "税抜き価格", class: "col-4" %>
         <%= f.text_field :price, class: "col-7" %>円
        </div>

        <div class='form-group row'>
         <%= f.label :is_active, "販売ステータス", class: "col-4" %>
         <h5><%= f.radio_button :is_active, true %>販売中</h5>
         <h5 class= "ml-3"><%= f.radio_button :is_active, false %> 販売停止</h5>
         </div>

        <div class="text-center"><%= f.submit '新規投稿',class:"btn btn-success" %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
 <h4 class= "mt-3 mb-5">商品詳細</h4>
 <div class="container">
  <div class="row">
   <div class="col-md-3">
    <%= image_tag @item.get_image(300, 300) %>
   </div>

   <div class="col-md-9">
    <div class="row">
     <div class="col-md-3 mb-2">
      商品名
     </div>
     <div class="col-md-5">
      <%= @item.name %>
     </div>
    </div>
    <div class="row">
     <div class="col-md-3 mb-2">
      商品説明
     </div>
     <div class="col-md-5">
      <%= @item.introduction %>
     </div>
    </div>
    <div class="row">
     <div class="col-md-3 mb-2">
      ジャンル
     </div>
     <div class="col-md-5">
      <%= @item.genre.name %>
     </div>
    </div>
    <div class="row">
     <div class="col-md-3 mb-2">
      税込価格</br>
      (税抜価格)
     </div>
     <div class="col-md-5">
       <%= @item.with_tax_price %>円(<%= @item.price %>円)
     </div>
    </div>
    <div class="row">
     <div class="col-md-3 mb-2">
      販売ステータス
     </div>
     <div class="col-md-5">
       <% if @item.is_active == true %>
          販売中
       <% elsif @item.is_active == false %>
          販売停止中
       <% end %>
     </div>
    </div>
    <div class="offset-md-3">
    <%= link_to "編集する", edit_admin_item_path(@item.id),class:"btn btn-sm btn-success" %>
    </div>
   </div>
  </div>
 </div>

app/views/admin/orders/show.html.erb
<div class="container">
 <div class="col-md-12">
   <h4 class= "mt-3 mb-2">注文履歴詳細</h4>

   <div class="row">
    <div class="col-md-2 mb-2">
     <h5>購入者</h5>
    </div>
    <div class="col-md-5">
      <%= @order.customer.first_name %>
      <%= @order.customer.last_name %>
    </div>
   </div>
   <div class="row">
    <div class="col-md-2 mb-2">
     <h5>注文日</h5>
    </div>
    <div class="col-md-5">
      <%= @order.created_at.strftime('%Y/%m/%d') %>
    </div>
   </div>
   <div class="row">
    <div class="col-md-2 mb-2">
      <h5>お届け先</h5>
    </div>
    <div class="col-md-5">
       〒<%= @order.postal_code %>
     <%= @order.address %>
     <%= @order.name %>
    </div>
   </div>
   <div class="row">
    <div class="col-md-2 mb-2">
      <h5>支払方法</h5>
    </div>
    <div class="col-md-5">
       <%= Order.payment_methods_i18n[@order.payment_method] %>
    </div>
   </div>
   <div class="row">
    <div class="col-md-2 mb-2">
      <h5>注文ステータス</h5>
    </div>
    <div class="col-md-5">
     <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch do |f| %>
     <%= f.select :status, Order.statuses_i18n.keys.map{|k| [I18n.t("enums.order.status.#{k}"), k]} %>
     <%= f.submit "更新",class:"btn btn-success" %>
     <% end %>
    </div>
   </div>
  </div>
  <div class="mt-4 row">
   <table class="table col-md-8">
    <thead>
     <tr>
      <th>商品名</th>
      <th>単価(税込)</th>
      <th>数量</th>
      <th>小計</th>
      <th>製作ステータス</th>
     </tr>
    </thead>
      <% @order.order_ditails.each do |ditail| %>
    <tbody>
      <tr>
       <td><%= ditail.item.name %></td>
       <td><%= ditail.item.with_tax_price %></td>
       <td><%= ditail.amount %></td>
       <td><%= ditail.item.with_tax_price * ditail.amount %></td>
       <td>
        <%= form_with model: ditail, url: admin_order_ditail_path(ditail.id), method: :patch do |f| %>
        <%= f.select :making_status, OrderDitail.making_statuses_i18n.keys.map{|k| [I18n.t("enums.order_ditail.making_status.#{k}"), k]} %>
        <%= f.submit "更新",class:"btn btn-success" %>
        <% end %>
       </td>
         <% @total += ditail.item.with_tax_price * ditail.amount %>
      </tr>
        <% end %>
     </tbody>
    </table>
    <table class="col-md-2 offset-md-1 mt-auto"style='height:100px;'>
     <tr>
      <th>商品金額</th>
      <td><%= @total %>円</td>
     </tr>
     <tr>
      <th>送料</th>
      <td><%= @order.delivery_charge %>円</td>
     </tr>
     <tr>
      <th>請求金額合計</th>
      <td><%= @total + @order.delivery_charge %>円</td>
     </tr>
    </table>
 </div>
</div>