config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
 namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_ditails, only: [:update]
    root to: "homes#top"
 end

   scope module: :public do
   root to: "homes#top"
   get '/about' => 'homes#about', as: 'about'
   resources :items, only: [:index, :show]
   resource :customers, only: [:show, :edit, :update] do
   collection do
    get 'withdraw'
    patch 'unsubscribe'
   end
    end
   resources :cart_items, only: [:index, :create, :update, :destroy] do
   collection do
   delete 'destroy_all'
  end
   end
    resources :orders, only: [:index, :create, :new, :show] do
   collection do
   get 'complete'
   post 'confirm'
   end
   end
   resources :addresses, only: [:index, :create, :edit, :update, :destroy]
 end


  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
 belongs_to :customer
 def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
 end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 has_many :addresses, dependent: :destroy
 has_many :cart_items, dependent: :destroy
 has_many :orders, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
 has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
 belongs_to :genre
 has_many :cart_items, dependent: :destroy
 has_many :order_ditails, dependent: :destroy
 has_one_attached :image

 def get_image(width, height)
  unless image.attached?
    file_path = Rails.root.join('app/assets/images/no_image.jpg')
    image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  image.variant(resize_to_limit: [width, height]).processed
 end

 def with_tax_price
    (price * 1.1).floor
 end

end

app/models/order.rb
class Order < ApplicationRecord
 belongs_to :customer
 has_many :order_ditails, dependent: :destroy
enum payment_method: { credit_card: 0, transfer: 1 }
enum status: { waiting_for_payment: 0, payment_confirmation: 1, in_production: 2, preparing_for_shipment: 3, shipped: 4 }
 def subtotal
    item.with_tax_price * amount
 end
end

app/models/order_ditail.rb
class OrderDitail < ApplicationRecord
 belongs_to :order
 belongs_to :item
 enum making_status: { not_allowed_to_produce: 0, production_waiting: 1, in_production: 2, production_completed: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
 def index
  @genres = Genre.all
  @genre = Genre.new
 end

 def create
  @genre = Genre.new(genre_params)
  @genre.save
   redirect_to admin_genres_path
 end

 def edit
  @genre = Genre.find(params[:id])
 end

 def update
  @genre = Genre.find(params[:id])
  @genre.update(genre_params)
  redirect_to admin_genres_path(@genre.id)
 end

 private

 def genre_params
  params.require(:genre).permit(:name)
 end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
 before_action :authenticate_admin!
 def top
  @orders = Order.page(params[:page])
 end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
 def new
  @item = Item.new
 end

 def index
  @items = Item.all.page(params[:page])
 end

 def create
  @item = Item.new(item_params)
  @item.save
  redirect_to admin_item_path(@item.id)
 end

 def show
  @item = Item.find(params[:id])
 end

 def edit
  @item = Item.find(params[:id])
 end

 def update
  @item = Item.find(params[:id])
  @item.update(item_params)
  redirect_to admin_items_path(@item.id)
 end

 private

 def item_params
  params.require(:item).permit(:name,:introduction,:image,:genre_id,:price,:is_active)
 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_ditails_helper.rb
module Admin::OrderDitailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
       <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <h1 class="text-white border">LOGO</h1>
        <ul class="navbar-nav ml-auto">
           <% if customer_signed_in? %>
         <li>
           <%= link_to 'マイページ', customers_path, class:"btn btn-outline-light ml-5" %>
         </li>
         <li>
           <%= link_to '商品一覧', items_path, class:"btn btn-outline-light ml-5" %>
         </li>
         <li>
           <%= link_to 'カート', cart_items_path, class:"btn btn-outline-light ml-5" %>
         </li>
         <li>
          <%= link_to 'ログアウト', destroy_customer_session_path, method: :delete, class:"btn btn-outline-light ml-5" %>
         </li>
           <% elsif  admin_signed_in? %>
          <li>
           <%= link_to '商品一覧', admin_items_path, class:"btn btn-outline-light ml-5" %>
          </li>
          <li>
            <%= link_to '会員一覧', admin_customers_path, class:"btn btn-outline-light ml-5" %>
          </li>
          <li>
            <%= link_to '注文履歴一覧', admin_root_path, class:"btn btn-outline-light ml-5" %>
          </li>
          <li>
            <%= link_to 'ジャンル一覧', admin_genres_path, class:"btn btn-outline-light ml-5" %>
          </li>
          <li>
           <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class:"btn btn-outline-light ml-5" %>
          </li>
          <% else %>
          <li>
           <%= link_to 'About', about_path, class:"btn btn-outline-light ml-5" %>
          </li>
          <li>
            <%= link_to '商品一覧', items_path, class:"btn btn-outline-light ml-5" %>
          </li>
          <li>
           <%= link_to '新規登録', new_customer_registration_path, class:"btn btn-outline-light ml-5" %>
          </li>
          <li>
           <%= link_to 'ログイン', new_customer_session_path, class:"btn btn-outline-light ml-5" %>
          </li>
           <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
<main>
 <div class="container">
 <%= yield %>
 </div>
</main>
 <footer class= "bg-dark fixed-bottom" style= "height: 100px;">
  <div class="container mt-5">
  	<div class="row">
    <div class="mx-auto">
    </div>
   </div>
  </div>
 </footer>
 </body>
</html>